# Generated by setup_environment.ps1. This file is machine-local.
$env:PROJECTFOURIER_ROOT = 'C:\Users\27107\source\repos\ProjectFourier'
function Add-ProjectFourierPath([string]$PathItem) {
    if ($PathItem -and (Test-Path -LiteralPath $PathItem) -and (($env:PATH -split ';') -notcontains $PathItem)) {
        $env:PATH = "$PathItem;$env:PATH"
    }
}
$env:OPENCV_DIR = 'C:\Users\27107\Documents\openCV\opencv\build'
Add-ProjectFourierPath 'C:\Users\27107\Documents\openCV\opencv\build\x64\vc16\bin'
Add-ProjectFourierPath 'C:\Users\27107\Documents\POTRACE\potrace-1.16.win64'
